### ISSUE TITLE
How to convert mandalorion output psl to sqanti input gtf

### ISSUE THREAD

**Issue by JYLeeBioinfo** [rvolden/Mandalorion#4]
What tool do you use to conver psl to gtf?

I found some of the scripts for this purpose in some repositories but all that I tried were not working and no longer maintained.

**Comment by rvolden** [comment]
I haven't had to convert psl to gtf, but flair has a script that does it. Note that I haven't tested this, but [here it is.](https://github.com/BrooksLabUCSC/flair/blob/master/bin/psl_to_gtf.py)

**Comment by JYLeeBioinfo** [comment]
Thank you! I'll try that one.

**Comment by Olinewms** [comment]
Hi @rvolden, I'm looking through the python script you linked, but struggling to see where to input my .psl file. Could you please point me in the right direction? This is all kinda new to me. Cheers
